### ISSUE TITLE
Simple use-case does not work and logging does not show what is wrong

### ISSUE THREAD

**Issue by ArinRayAtCornerStoneFS** [tpunder/fm-sbt-s3-resolver#73]
This might be a non-issue but I've been at it since half a day so thought I'll see if I can get some help here.

I am trying to download a java jar from an amazon s3 bucket as a dependency

In my project/plugins.sbt (also tried putting this in project/project/plugins.sbt based on some internet forum)

`addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.21.0")` (accessible on maven)

In my build.sbt

`resolvers += "s3-bucket-release" at "s3://<my org name>/release" `  (I can access this location from my laptop cmd using simple AWS_ACCESS_KEY_ID and AWS_SECRET_KEY)

In my repositories file (also tried moving these to a resolvers ++= Seq(...))

```
[repositories]
  local
  maven-local
  typesafe-ivy-releases: https://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
  maven-central
  sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots
```

Finally, when I do

`AWS_ACCESS_KEY_ID=XXXXX AWS_SECRET_KEY=XXXX sbt update -v`

I see 

```
[info] Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
[info] Creating a new Ivy URLHandlerDispatcher to handle s3:// URLs
```

But then 

```
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.myorg.subdomain:com.myorg.subdomain.libname:0.0.1
[error]   Not found
[error]   Not found
[error]   not found: /Users/arindamray/.ivy2/localcom.myorg.subdomain/com.myorg.subdomain.libname/0.0.1/ivys/ivy.xml
[error]   not found: /Users/arindamray/.m2/repository/com/myorg/subdomain/messaging/com.myorg.subdomain.libname/0.0.1/com.myorg.subdomain.libname-0.0.1.pom
[error]   not found: https://repo1.maven.org/maven2/com/myorg/subdomain/messaging/com.myorg.subdomain.libname/0.0.1/com.myorg.subdomain.libname-0.0.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/myorg/subdomain/messaging/com.myorg.subdomain.libname/0.0.1/com.myorg.subdomain.libname-0.0.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.myorg.subdomain/com.myorg.subdomain.libname/0.0.1/ivys/ivy.xml
[error]     at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error]     at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error]     at scala.util.Either$LeftProjection.map(Either.scala:573)
....
```

It seems it is not looking at the s3 bucket for the library at all.

What am I doing wrong here?

**Comment by tpunder** [comment]
I don't see any obviously wrong.

A few questions:

- What is the repositories file?
- Can you post a more complete example?

**Comment by tpunder** [comment]
Here is a really old example of 2 minimal projects that were working for me at the time: https://github.com/tpunder/fm-sbt-s3-resolver-issue-26

The fm-sbt-s3-resolver plugin version and SBT versions are all old (you would want to use the latest ones) but the basic usage is still the same.

**Comment by ArinRayAtCornerStoneFS** [comment]
🤦 
I had these in a file called .jvmopts in the root of the project and I did not guess they would interfere with plugin behaviour.
```
-Dsbt.override.build.repos=true
-Dsbt.repository.config=./project/repositories
```
(hence the repositories file)
Removing them did the trick.
The sample repos defo helped in diagnosing this. Thanks a ton!
